pipeline {
    agent any
    environment {
        OWNER = 'cursus-studio'
        CONTEXT = 'jenkins/ci-cd'
        REPO = 'texhec'
    }

    stages {
        stage('Loading') {
            steps {
                withCredentials([githubApp(credentialsId: 'texhec-app', variable: 'TOKEN')]) {
                    script {
                        updateGitHubStatus('pending', 'Build is in progress...', TOKEN)
                    }
                }
            }
        }
    // stage('Sync Repo') {
    //     steps {
    //         checkout scm
    //     }
    // }
    }
    post {
        //  always {
        //          echo 'Cleanup'
        //  }
        success {
            // updateGitHubStatus('success', 'Pipeline passed!')
            withCredentials([githubApp(credentialsId: 'texhec-app', variable: 'TOKEN')]) {
                    script {
                        updateGitHubStatus('success', 'Pipeline passed!', TOKEN)
                    }
            }
        }
        failure {
            // updateGitHubStatus('failure', 'Pipeline failed!')
            withCredentials([githubApp(credentialsId: 'texhec-app', variable: 'TOKEN')]) {
                    script {
                        updateGitHubStatus('failure', 'Pipeline failed!', TOKEN)
                    }
            }
        }
    }
}

def updateGitHubStatus(String state, String description, String token) {
    sh """
        curl -L -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${token}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${OWNER}/${REPO}/statuses/${GIT_COMMIT} \
        -d "{\\"state\\":\\"${state}\\",\\"target_url\\":\\"${BUILD_URL}\\",\\"description\\":\\"${description}\\",\\"context\\":\\"${CONTEXT}\\"}"
    """
}
