// TODO:
// - stop using ./set_status.sh and start using some jenkins extension
// - start using proper error handling
def modules = ['engine', 'core']

pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'ci-cd'
            args '-v /home/jenkins/go-cache:/root/.cache/go-build -v /home/jenkins/golangci-lint:/root/.cache/golangci-lint'
            // Necessary for OpenGL/Graphics testing if running on a headful agent
            additionalBuildArgs  '--build-arg CACHE_DATE=$(date +%Y-%m-%d)'
        }
    }
    triggers {
        githubPush()
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20'))
    }
    environment {
        CONTEXT = 'jenkins/ci-cd'

        OWNER = 'cursus-studio'
        REPO = 'texhec'
    }

    stages {
        stage('Initializing') {
            steps {
                checkout scm
                sh 'go version'
                sh 'golangci-lint --version'
            }
        }
        stage('Setup dependencies') {
            steps {
                script {
                    updateGitHubStatus('pending', 'Loading dependencies...')
                    def tasks = [:]
                    modules.each { mod ->
                        tasks[mod] = {
                            dir("${env.WORKSPACE}/${mod}") {
                                sh 'go mod download'
                                sh 'go mod tidy -diff'
                                sh 'go mod verify'
                            }
                        }
                    }
                    parallel tasks
                }
            }
        }
        stage('Tests') {
            steps {
                script {
                    updateGitHubStatus('pending', 'Testing ...')
                    def tasks = [:]
                    modules.each { mod ->
                        tasks[mod] = {
                            dir("${env.WORKSPACE}/${mod}") {
                                sh 'go test ./...'
                            }
                        }
                    }
                    parallel tasks
                }
            }
        }
        stage('Linting') {
            steps {
                script {
                    updateGitHubStatus('pending', 'Linting...')
                    def tasks = [:]
                    modules.each { mod ->
                        tasks[mod] = {
                            dir("${env.WORKSPACE}/${mod}") {
                                sh 'golangci-lint run'
                            }
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            updateGitHubStatus('success', 'Success!')
        }
        failure {
            updateGitHubStatus('failure', "Build failed at stage: \"${env.LAST_STATUS_DESC}\"")
        }
    }
}

def updateGitHubStatus(String state, String desc) {
    env.LAST_STATUS_DESC = desc
    dir("${env.WORKSPACE}/ci-cd") {
        withCredentials([usernamePassword(credentialsId: 'texhec-app', passwordVariable: 'TOKEN', usernameVariable: 'USER')]) {
            withEnv([
            "GIT_COMMIT=${env.GIT_COMMIT}",
            "TARGET_URL=${env.BUILD_URL}",
            "STATE=${state}",
            "DESC=${desc}",
        ]) {
                sh 'bash set_status.sh'
        }
        }
    }
}
