pipeline {
    // agent any // agent should have sdl2, opengl, golang lint and golang
    agent {
            dockerfile {
                filename 'Dockerfile'
                dir 'ci-cd'
                // Necessary for OpenGL/Graphics testing if running on a headful agent
                additionalBuildArgs  '--build-arg CACHE_DATE=$(date +%Y-%m-%d)'
            }
    }
    environment {
        CONTEXT = 'jenkins/ci-cd'

        OWNER = 'cursus-studio'
        REPO = 'texhec'
    }

    stages {
        stage('Initializing') {
            steps {
                checkout scm
                updateGitHubStatus('pending', 'Build is in progress...')
            }
        }
        stage('Engine: Lint & Test') {
            steps {
                dir('engine') {
                    updateGitHubStatus('pending', 'Engine: Lint & Test...')
                    sh 'golangci-lint run --timeout=5m'
                    sh 'go test ./...'
                }
            }
        }
        stage('Core: Lint & Test') {
            steps {
                dir('core') {
                    updateGitHubStatus('pending', 'Core: Lint & Test')
                    sh 'golangci-lint run --timeout=5m'
                    sh 'go test ./...'
                }
            }
        }
    }
    post {
        success {
            updateGitHubStatus('success', 'All tests passed!')
        }
        failure {
            updateGitHubStatus('failure', 'Tests failed!')
        }
    }
}

def updateGitHubStatus(String STATE, String DESC) {
    withCredentials([usernamePassword(credentialsId: 'texhec-app', passwordVariable: 'TOKEN', usernameVariable: 'USER')]) {
        withEnv([
            "GIT_COMMIT=${env.GIT_COMMIT}",
            "TARGET_URL=${env.BUILD_URL}",
            "STATE=${STATE}",
            "DESC=${DESC}",
        ]) {
                dir("${env.WORKSPACE}/ci-cd") {
                sh 'bash set_status.sh'
                }
        }
    }
}
